// Base de descrições de materiais (código SAP -> texto breve material)
// Gerada a partir do cadastro de materiais fornecido.

export type MaterialInfo = { descricao: string; categoria: string }

export const materiaisInfo: Record<string, MaterialInfo> = {
  "256144": { descricao: "BOLINHO QUEIJ/PRES PRE FRITO NORD 300G", categoria: "Salgados" },
  "256135": { descricao: "BOLINHO QUEIJO CONG AIR FRYER NORD 300G", categoria: "Salgados" },
  "254244": { descricao: "CHURROS DOCE LEITE FAB PROP CG KG", categoria: "Salgados" },
  "256153": { descricao: "COXINHA FRANGO CONG AIR FRYER NORD 300G", categoria: "Salgados" },
  "255127": { descricao: "CROISSANT FAB PROPRIA CG UN", categoria: "Doces & Especiais" },
  "255925": { descricao: "DONUTS MASSA BASE PRD KG", categoria: "Doces & Especiais" },
  "252196": { descricao: "FOCACCIA FAB PROPRIA CG KG", categoria: "Doces & Especiais" },
  "250432": { descricao: "FRANCESINHO MINI CONG KG", categoria: "Doces & Especiais" },
  "925122": { descricao: "MASSA BASE FAB PROPRIA KG", categoria: "Doces & Especiais" },
  "2028726": { descricao: "MASSA BASE PANETONE C GOTAS FP CG KG", categoria: "Doces & Especiais" },
  "252216": { descricao: "MASSA PARA PIZZAS FAB PROPRIA 660G", categoria: "Pizzas" },
  "254502": { descricao: "MASSA PIZZA FAB. PROPRIA 400G", categoria: "Pizzas" },
  "2000023": { descricao: "MP ACUCAR REFINADO KG", categoria: "Matéria-prima" },
  "2019054": { descricao: "MP AMIDMAIS", categoria: "Matéria-prima" },
  "2000030": { descricao: "MP ANTIMOFO KG", categoria: "Matéria-prima" },
  "2000054": { descricao: "MP CEBOLA BRANCA", categoria: "Matéria-prima" },
  "2000056": { descricao: "MP CENOURA CFLV KG", categoria: "Matéria-prima" },
  "2029389": { descricao: "MP ERVAS FINAS", categoria: "Matéria-prima" },
  "2021632": { descricao: "MP FARINHA DE TRIGO EXTRA CLARA KG", categoria: "Matéria-prima" },
  "2000092": { descricao: "MP FIBRA DE TRIGO KG", categoria: "Matéria-prima" },
  "2000104": { descricao: "MP GEMA LIQUIDA KG", categoria: "Matéria-prima" },
  "2000106": { descricao: "MP GORDURA VEGETAL KG", categoria: "Matéria-prima" },
  "2000114": { descricao: "MP LEITE UHT L", categoria: "Matéria-prima" },
  "2000115": { descricao: "MP LINGUICA CALABRESA KG", categoria: "Matéria-prima" },
  "2000121": { descricao: "MP MARGARINA KG", categoria: "Matéria-prima" },
  "2000122": { descricao: "MP MARGARINAS ESPECIAIS KG", categoria: "Matéria-prima" },
  "2000151": { descricao: "MP OVOS KG", categoria: "Matéria-prima" },
  "2000154": { descricao: "MP PASTA DE ALHO KG", categoria: "Matéria-prima" },
  "2000156": { descricao: "MP PEITO DE FRANGO DESFIADO", categoria: "Matéria-prima" },
  "257158": { descricao: "MP PRE MIST VOLLGUT IREKS KG", categoria: "Matéria-prima" },
  "2000165": { descricao: "MP PRESUNTO KG", categoria: "Matéria-prima" },
  "2017178": { descricao: "MP QUEIJO COALHO KG", categoria: "Matéria-prima" },
  "2000168": { descricao: "MP QUEIJO MANTEIGA KG", categoria: "Matéria-prima" },
  "2000184": { descricao: "MP REQUEIJAO KG", categoria: "Matéria-prima" },
  "2000189": { descricao: "MP SALSICHA KG", categoria: "Matéria-prima" },
  "2027620": { descricao: "MP TRIGO DE KIBE KG", categoria: "Matéria-prima" },
  "254410": { descricao: "PANETONE FRUTAS SACO 400G UN", categoria: "Doces & Especiais" },
  "254367": { descricao: "PANETONE GOTAS CHOCOLATE FP PC 400G", categoria: "Doces & Especiais" },
  "256353": { descricao: "PAO ALHO PICANTE FAB PROPRIA 350G", categoria: "Pães" },
  "255434": { descricao: "PAO ALHO TRADICIONAL FAB PROPRIA 350G", categoria: "Pães" },
  "255866": { descricao: "PAO AUSTRALIANO FAB PROPRIA KG", categoria: "Pães" },
  "250661": { descricao: "PAO BAGUETE CG KG", categoria: "Pães" },
  "250668": { descricao: "PAO BATATA FAB PROPRIA KG", categoria: "Pães" },
  "255878": { descricao: "PAO BRIOCHE FAB PROPRIA ESPECIAL KG", categoria: "Pães" },
  "255894": { descricao: "PAO BRIOCHE FAB PROPRIA INT KG", categoria: "Pães" },
  "255873": { descricao: "PAO BRIOCHE FAB PROPRIA KG", categoria: "Pães" },
  "255859": { descricao: "PAO BRIOCHE FAB PROPRIA LEITE KG", categoria: "Pães" },
  "255617": { descricao: "PAO BRIOCHE PROVOLONE FAB PROPRIA KG", categoria: "Pães" },
  "250679": { descricao: "PAO CARTEIRA FAB PROPRIA CG KG", categoria: "Pães" },
  "250681": { descricao: "PAO CEIA FAB PROPRIA CG KG", categoria: "Pães" },
  "250683": { descricao: "PAO CENOURA FAB PROPRIA KG", categoria: "Pães" },
  "250687": { descricao: "PAO DOCE FAB PROPRIA C/COCO CG KG", categoria: "Pães" },
  "255422": { descricao: "PAO FERM NAT AZEITONA CG KG", categoria: "Pães" },
  "255415": { descricao: "PAO FERM NAT CALABRESA CG KG", categoria: "Pães" },
  "255417": { descricao: "PAO FERM NAT GORGONZOLA E NOZES CG KG", categoria: "Pães" },
  "250692": { descricao: "PAO FOLHA FAB PROPRIA CG KG", categoria: "Pães" },
  "257062": { descricao: "PAO FORMA 39% INTEGRAL 350G", categoria: "Pães" },
  "255942": { descricao: "PAO FORMA DE LEITE FAB PROPRIA 400G", categoria: "Pães" },
  "250695": { descricao: "PAO FORMA FAB PROPRIA BABY INT KG", categoria: "Pães" },
  "250696": { descricao: "PAO FORMA FAB PROPRIA BABY KG", categoria: "Pães" },
  "257648": { descricao: "PAO FORMA TRADICIONAL 350G", categoria: "Pães" },
  "255836": { descricao: "PAO FRANCES FAB PROPRIA CG KG", categoria: "Pães" },
  "250701": { descricao: "PAO FRANCES FAB PROPRIA INTEGRAL CG KG", categoria: "Pães" },
  "250704": { descricao: "PAO FRANCES PRE-ASSADO TRAD CONG KG", categoria: "Pães" },
  "252703": { descricao: "PAO HAMBURGUER AUSTRALIANO FAB PROP", categoria: "Pães" },
  "252713": { descricao: "PAO HAMBURGUER BATATA FAB PROP KG", categoria: "Pães" },
  "250710": { descricao: "PAO HAMBURGUER FAB PROP 35% INTEGRAL KG", categoria: "Pães" },
  "256184": { descricao: "PAO HAMBURGUER FAB PROPRIA 440G", categoria: "Pães" },
  "250709": { descricao: "PAO HAMBURGUER FAB PROPRIA GERGELIM KG", categoria: "Pães" },
  "252718": { descricao: "PAO HAMBURGUER MANDIOQUINHA FAB PROP KG", categoria: "Pães" },
  "250728": { descricao: "PAO HOT DOG FAB PROP 350G", categoria: "Pães" },
  "255830": { descricao: "PAO ITALIANO FAB PROPRIA CG KG", categoria: "Pães" },
  "250714": { descricao: "PAO LARANJA FAB PROPRIA KG", categoria: "Pães" },
  "250715": { descricao: "PAO LEITE FAB PROPRIA KG", categoria: "Pães" },
  "250717": { descricao: "PAO MANDIOQUINHA FAB PROPRIA KG", categoria: "Pães" },
  "256357": { descricao: "PAO PORTUGUES CG KG", categoria: "Pães" },
  "255803": { descricao: "PAO QUEIJO ESPECIAL FAB PROP KG", categoria: "Pães" },
  "250723": { descricao: "PAO QUEIJO FAB PROPRIA KG", categoria: "Pães" },
  "250724": { descricao: "PAO QUEIJO MINEIRO FAB PROPRIA CG KG", categoria: "Pães" },
  "255753": { descricao: "PAO QUEIJO MINEIRO RECEITA DA GENTE 400G", categoria: "Pães" },
  "250727": { descricao: "PAO RECIFE FAB PROPRIA KG", categoria: "Pães" },
  "253410": { descricao: "PAO RUSTICO COM ERVAS CG FAB PROPRIA KG", categoria: "Pães" },
  "253345": { descricao: "PAO RUSTICO DARK CAST CAJU FAB PRO CG KG", categoria: "Pães" },
  "250729": { descricao: "PAO SANDUICHE INT FAB PROPRIA KG", categoria: "Pães" },
  "255879": { descricao: "PAO SEMI-ITALIANO FAB PROPRIA KG", categoria: "Pães" },
  "250732": { descricao: "PAO SIRIO FAB PROPRIA KG", categoria: "Pães" },
  "250737": { descricao: "PAO SUICO FAB PROPRIA KG", categoria: "Pães" },
  "256439": { descricao: "PAO TAPIOCA FAB PROPRIA KG", categoria: "Pães" },
  "255883": { descricao: "PAO TRANCA DE FRUTAS FAB PROPRIA KG", categoria: "Pães" },
  "254495": { descricao: "PIZZA FAB PROP CALABRESA PESO LIQ 400G", categoria: "Pizzas" },
  "254504": { descricao: "PIZZA FAB PROP FRANGO PESO LIQ 400G", categoria: "Pizzas" },
  "254501": { descricao: "PIZZA FAB PROP MUSSARELA PESO LIQ 400G", categoria: "Pizzas" },
  "254494": { descricao: "PIZZA FAB PROP PRES/CALAB PESO LIQ 400G", categoria: "Pizzas" },
  "254509": { descricao: "PIZZA FAB PROP QUEIJO/PRESUNTO 400G", categoria: "Pizzas" },
  "255881": { descricao: "PIZZA FAB PROP SERTANEJA 400G", categoria: "Pizzas" },
  "925004": { descricao: "RECHEIO BOLINHO CARNE BUFFET", categoria: "Recheio" },
  "925006": { descricao: "RECHEIO BOLINHO QUEIJO/PRES BUFFET", categoria: "Recheio" },
  "925007": { descricao: "RECHEIO FOLHADO DE FRANGO", categoria: "Recheio" },
  "925010": { descricao: "RECHEIO FOLHADO QUEIJO/PRESUNTO KG.", categoria: "Recheio" },
  "925009": { descricao: "RECHEIO FRANGO P/COXINHA KG", categoria: "Recheio" },
  "925016": { descricao: "RECHEIO TORTA FRANGO", categoria: "Recheio" },
  "251056": { descricao: "SALG BOLINHO QUEIJO CONG KG", categoria: "Salgados" },
  "251057": { descricao: "SALG BOLINHO QUEIJO/PRES CONG KG", categoria: "Salgados" },
  "253337": { descricao: "SALG CARNE C/ REQUEIJAO CONG UM FAB PRO", categoria: "Salgados" },
  "253350": { descricao: "SALG COXINHA FRANGO C/ REQUEIJAO CG", categoria: "Salgados" },
  "251060": { descricao: "SALG COXINHA FRANGO CONG KG", categoria: "Salgados" },
  "251061": { descricao: "SALG COXINHA FRANGO CONG UN", categoria: "Salgados" },
  "251062": { descricao: "SALG FOLHADO FAB PROPRIA FRANGO CG UN", categoria: "Salgados" },
  "251063": { descricao: "SALG FOLHADO FAB PROPRIA PRES/QUEI CG UN", categoria: "Salgados" },
  "251064": { descricao: "SALG FOLHADO FAB PROPRIA QUEIJO CG UN", categoria: "Salgados" },
  "251065": { descricao: "SALG FOLHADO FAB PROPRIA SALSICHA CG UN", categoria: "Salgados" },
  "255910": { descricao: "SONHO MASSA BASE PRD KG", categoria: "Doces & Especiais" },
  "251132": { descricao: "TORTA SALG FRANGO CG KG", categoria: "Salgados" },
}

export function getMaterialInfo(codigo: string): MaterialInfo {
  return materiaisInfo[codigo] ?? { descricao: "Material não cadastrado", categoria: "Outros" }
}

export function getMaterialDescricao(codigo: string): string {
  return materiaisInfo[codigo]?.descricao ?? codigo
}

export function getMaterialCategoria(codigo: string): string {
  return materiaisInfo[codigo]?.categoria ?? "Outros"
}
